apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  devtron-cluster
  region: ap-south-1
  version: "1.30"

vpc:
## Make sure that this CIDR doesn't overlaps with any other exisiting VPC with which a peering needs to be done.
  cidr: "10.30.0.0/16"

# By default, Amazon EKS automatically installs three essential networking add-ons: the Amazon VPC CNI plugin, kube-proxy, and CoreDNS
# https://www.eksworkshop.com/docs/fundamentals/storage/ebs/ebs-csi-driver
addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
    configurationValues: |
      {
        "defaultStorageClass": {
          "enabled": true
        }
      }
      
nodeGroups:
  - name: devtron-nodes
    privateNetworking: true
    availabilityZones:
      - ap-south-1a
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    instancesDistribution:
      maxPrice: 1.5
      instanceTypes: ["c5a.xlarge", "r5a.xlarge", "m5a.xlarge"]
      onDemandBaseCapacity: 2
      onDemandPercentageAboveBaseCapacity: 100
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::xxxxxxxxxxxxx:policy/devtron-cluster-IAM-policy
    ssh:
      allow: true
      publicKeyName: "infra"
    volumeSize: 50
    volumeType: gp3
    asgSuspendProcesses: ["AZRebalance"]
    tags:
      Component : cicd
    kubeletExtraConfig:
        kubeReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        cpuManagerPolicy: "static"
        systemReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            RotateKubeletServerCertificate: true
            CPUManager: true

  - name: ci-nodes
    privateNetworking: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 5
    instancesDistribution:
      maxPrice: 1.5
      instanceTypes: ["c5a.xlarge", "r5a.xlarge", "m5a.xlarge"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::xxxxxxxxxxxxx:policy/devtron-cluster-IAM-policy
    ssh:
      allow: true
      publicKeyName: "infra"
    volumeSize: 100
    volumeType: gp3
    asgSuspendProcesses: ["AZRebalance"]
    tags:
      Component : cicd
    labels: {purpose: ci}
    taints:
      dedicated: "ci:NoSchedule"
    kubeletExtraConfig:
        kubeReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            RotateKubeletServerCertificate: true
