apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    purpose: pod-example
spec:
  containers:
  - name: pod-example
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure

