apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-example
  namespace: xyz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xyz
subjects:
  - kind: ServiceAccount
    name: xyz
    namespace: xyz

