{
 "title": "Devtron Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Argo Rollout metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "Total Rollouts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(rollout_info)" }
   ]
  },
  {
   "title": "Rollouts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rollout_info) by (strategy)"
    }
   ]
  },
  {
   "title": "Reconcile Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(rollout_reconcile_error)" }
   ]
  },
  {
   "title": "Stable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rollout_phase{phase=\"Completed\"} == 1)"
    }
   ]
  },
  {
   "title": "Progressing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rollout_phase{phase=\"Progressing\"})"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rollout_phase{phase=\"Paused\"} == 1)"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rollout_phase{phase=\"Error\"} == 1)"
    }
   ]
  },
  {
   "title": "Invalid Spec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rollout_phase{phase=\"InvalidSpec\"} == 1)"
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rollout_phase{phase=\"Timeout\"} == 1)"
    }
   ]
  },
  {
   "title": "Reconcile Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rollout_reconcile_count[10m]))"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(rollout_reconcile_bucket[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argo-rollouts-metrics\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "ArgoCD Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Clusters",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info{namespace=~\"devtroncd\"}))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"devtroncd\"})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{namespace=~\"devtroncd\"}))"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"devtroncd\"})"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"devtroncd\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "ArgoCD Health Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"devtroncd\", health_status!=\"\"}) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "ArgoCD Sync Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"devtroncd\",sync_status!=\"\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "ArgoCD Pending kubectl run",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_kubectl_exec_pending{namespace=~\"devtroncd\"}) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Sync Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(argocd_app_sync_total{namespace=~\"devtroncd\"})) by (grouping)",
     "legendFormat": "{{grouping}}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(round(argocd_app_sync_total{namespace=~\"devtroncd\",phase=~\"Error|Failed\"})) by (grouping, phase)",
     "legendFormat": "{{phase}}: {{grouping}}"
    }
   ]
  },
  {
   "title": "Reconciliation Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_count{namespace=\"devtroncd\"}[5m])) by (grouping)",
     "legendFormat": "{{grouping}}"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_app_k8s_request_total{namespace=\"devtroncd\"}[5m])) by (verb, resource_kind)",
     "legendFormat": "{{verb}} {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Argocd CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"argocd-metrics\",namespace=~\"devtroncd\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Argocd Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-metrics\",namespace=~\"devtroncd\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"argocd-metrics\",namespace=~\"devtroncd\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Resource Objects Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_cluster_api_resource_objects{namespace=~\"devtroncd\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "API Resources Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(argocd_cluster_api_resources{namespace=~\"devtroncd\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Cluster Events Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_cluster_events_total{namespace=~\"devtroncd\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Requests by result",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_redis_request_total{namespace=~\"devtroncd\"}) by (failed)",
     "legendFormat": "{{failed}}"
    }
   ]
  },
  { "title": "CPU Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "CPU throttling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"devtroncd\", container!=\"\"}[5m])) by (container) /sum(increase(container_cpu_cfs_periods_total{namespace=\"devtroncd\", container!=\"\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"devtroncd\", container_name!=\"\"}[5m])) by (container_name) /sum(increase(container_cpu_cfs_periods_total{namespace=\"devtroncd\", container_name!=\"\"}[5m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"devtroncd\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"devtroncd\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU requests and limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=\"devtroncd\",resource=\"cpu\",container!=\"\"}\n) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=\"devtroncd\",resource=\"cpu\",container_name!=\"\"}\n) by (container_name)",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"devtroncd\",resource=\"cpu\",container!=\"\"}\n) by (container)\r",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"devtroncd\",resource=\"cpu\",container_name!=\"\"}\n)\r by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"devtroncd\",container!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"devtroncd\",container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory requests and limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "\r\nsum(\n    kube_pod_container_resource_requests{namespace=\"devtroncd\",resource=\"memory\", container!=\"\"}\n) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=\"devtroncd\",resource=\"memory\", container_name!=\"\"}\n) by (container_name)",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"devtroncd\",resource=\"memory\",container!=\"\"}\n) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"devtroncd\",resource=\"memory\",container_name!=\"\"}\n) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Orchestrator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "Orchestrator Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_notifications_latency_seconds",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Orchestrator CPU consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"devtroncd\"}[10m]) *06",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Orchestrator_bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(orchestrator_http_duration_seconds_bucket[10m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Orchestrator-duration-count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(orchestrator_http_duration_seconds_count[10m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Orchestrator-duration-sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(orchestrator_http_duration_seconds_sum[10m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Orchestrator-request-current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "orchestrator_http_requests_current",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Orchestrator-requests-total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(orchestrator_http_requests_total[5m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "PVC Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "Git-sensor Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", namespace=\"devtroncd\", persistentvolumeclaim=\"git-volume-git-sensor-0\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{ job=\"kubelet\", namespace=\"devtroncd\", persistentvolumeclaim=\"git-volume-git-sensor-0\"})\n)\n",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{ job=\"kubelet\", namespace=\"devtroncd\", persistentvolumeclaim=\"git-volume-git-sensor-0\"})\n",
     "legendFormat": "Free Space"
    }
   ]
  },
  {
   "title": "Postgresql Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", namespace=\"devtroncd\", persistentvolumeclaim=\"data-postgresql-postgresql-0\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{ job=\"kubelet\", namespace=\"devtroncd\", persistentvolumeclaim=\"data-postgresql-postgresql-0\"})\n)\n",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{ job=\"kubelet\", namespace=\"devtroncd\", persistentvolumeclaim=\"data-postgresql-postgresql-0\"})\n",
     "legendFormat": "Free Space"
    }
   ]
  },
  { "title": "Devtron alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 } },
  { "title": "Devtron Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 220 } },
  {
   "title": "CI Triggers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(changes(ci_trigger_counter[10m]))",
     "legendFormat": "{{appId}}"
    }
   ]
  }
 ]
}