{
 "title": "Devtron-Usage",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\"}, label_app)"
   },
   {
    "name": "release",
    "label": "release",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_app=\"$service\"}, label_release)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node - Total Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "PV - Total Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_labels)"
    }
   ]
  },
  {
   "title": "Node - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[24h]) + avg_over_time(node_memory_Cached_bytes[24h]) + avg_over_time(node_memory_Buffers_bytes[24h])) / avg_over_time(node_memory_MemTotal_bytes[24h])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PVC - Total Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_labels)"
    }
   ]
  },
  {
   "title": "Pod - CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"$service\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pod - Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"$service\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pod - Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"$service\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pod - CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", container=\"$service\"}[5m])) by (container) / sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", container=\"$service\"}[5m])) by (container)"
    }
   ]
  },
  {
   "title": "Pod - CPU Quota",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "vCPU" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$service\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "TOTAL LIMIT"
    }
   ]
  },
  {
   "title": "Pod - Memory Quota",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$service\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$service\"})",
     "legendFormat": "TOTAL LIMIT"
    }
   ]
  },
  {
   "title": "Autoscaling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"keda-hpa-[[release]]-keda\",namespace=\"$namespace\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"[[release]]-hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"keda-hpa-[[release]]-keda\",namespace=\"$namespace\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"[[release]]-hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"keda-hpa-[[release]]-keda\",namespace=\"$namespace\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"[[release]]-hpa\",namespace=\"$namespace\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"keda-hpa-[[release]]-keda\",namespace=\"$namespace\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"[[release]]-hpa\",namespace=\"$namespace\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Response Code - 2xx ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq{response_code_class=\"2xx\",namespace=\"$namespace\",service=~\"[[release]]-service\"}[2m]) / 2",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod - Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=~\"[[release]]-service\"}[2m]) / 2",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response Code - 4xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq{response_code_class=\"4xx\",namespace=\"$namespace\",service=~\"[[release]]-service\"}[2m]) / 2",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response Code - 3xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq{response_code_class=\"3xx\",namespace=\"$namespace\",service=~\"[[release]]-service\"}[2m]) / 2",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response Code - 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq{response_code_class=\"5xx\",namespace=\"$namespace\",service=~\"[[release]]-service\"}[2m]) / 2",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}