{
 "title": "Orchestrator API Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "status",
    "query": "label_values(orchestrator_http_requests_total, status)"
   },
   {
    "name": "time_range",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "API Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Orchestrator API",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total{status=\"$status\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"$status\",ingress=\"devtron-ingress\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total[$time_range]))"
    }
   ]
  },
  {
   "title": "404 Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total{status=\"404\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "401 Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total{status=\"401\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "403 Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total{status=\"403\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "500 Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total{status=\"500\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "502 Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total{status=\"502\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "503 Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total{status=\"503\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "504 Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(orchestrator_http_requests_total{status=\"504\"}[$time_range]))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"orchestrator\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"orchestrator.*\", resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"orchestrator.*\", resource=\"cpu\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=~\"orchestrator.*\", container!=\"\"}[5m])) by (container) /sum(increase(container_cpu_cfs_periods_total{pod=~\"orchestrator.*\", container!=\"\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"orchestrator.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"orchestrator.*\", resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"orchestrator.*\", resource=\"memory\"})",
     "legendFormat": "limits"
    }
   ]
  }
 ]
}